<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130611170618 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_team (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_account (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_account_events_join (scoutrace_account VARCHAR(40) NOT NULL, scoutrace_event VARCHAR(40) NOT NULL, INDEX IDX_68783696F52C55C0 (scoutrace_account), INDEX IDX_68783696D5C582FE (scoutrace_event), PRIMARY KEY(scoutrace_account, scoutrace_event))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_event (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_event_organizers_join (scoutrace_event VARCHAR(40) NOT NULL, scoutrace_account VARCHAR(40) NOT NULL, INDEX IDX_B77A0A28D5C582FE (scoutrace_event), INDEX IDX_B77A0A28F52C55C0 (scoutrace_account), PRIMARY KEY(scoutrace_event, scoutrace_account))");
		$this->addSql("CREATE TABLE scoutrace_scoutrace_domain_model_activity (persistence_object_identifier VARCHAR(40) NOT NULL, event VARCHAR(40) DEFAULT NULL, INDEX IDX_BC1FDCBB3BAE0AA7 (event), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_account ADD CONSTRAINT FK_CC99ED3E47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_account_events_join ADD CONSTRAINT FK_68783696F52C55C0 FOREIGN KEY (scoutrace_account) REFERENCES scoutrace_scoutrace_domain_model_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_account_events_join ADD CONSTRAINT FK_68783696D5C582FE FOREIGN KEY (scoutrace_event) REFERENCES scoutrace_scoutrace_domain_model_event (persistence_object_identifier)");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_event_organizers_join ADD CONSTRAINT FK_B77A0A28D5C582FE FOREIGN KEY (scoutrace_event) REFERENCES scoutrace_scoutrace_domain_model_event (persistence_object_identifier)");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_event_organizers_join ADD CONSTRAINT FK_B77A0A28F52C55C0 FOREIGN KEY (scoutrace_account) REFERENCES scoutrace_scoutrace_domain_model_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_activity ADD CONSTRAINT FK_BC1FDCBB3BAE0AA7 FOREIGN KEY (event) REFERENCES scoutrace_scoutrace_domain_model_event (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_account_events_join DROP FOREIGN KEY FK_68783696F52C55C0");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_event_organizers_join DROP FOREIGN KEY FK_B77A0A28F52C55C0");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_account_events_join DROP FOREIGN KEY FK_68783696D5C582FE");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_event_organizers_join DROP FOREIGN KEY FK_B77A0A28D5C582FE");
		$this->addSql("ALTER TABLE scoutrace_scoutrace_domain_model_activity DROP FOREIGN KEY FK_BC1FDCBB3BAE0AA7");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_team");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_answer");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_account");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_account_events_join");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_event");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_event_organizers_join");
		$this->addSql("DROP TABLE scoutrace_scoutrace_domain_model_activity");
	}
}

?>